[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "nodejs_18"]

[phases.install]
cmds = [
    "python -m venv /opt/venv",
    ". /opt/venv/bin/activate && pip install --upgrade pip",
    ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Build phase complete'"]

[start]
cmd = ". /opt/venv/bin/activate && python -m uvicorn backend.main:app --host 0.0.0.0 --port $PORT"

[variables]
PATH = "/opt/venv/bin:$PATH"
