[phases.setup]
nixPkgs = ['python311', 'nodejs_18']

[phases.install]
cmds = ['pip install -r requirements.txt']

[phases.build]
cmds = ['echo "Build phase complete"']

[start]
cmd = 'magentic-ui --host 0.0.0.0 --port $PORT --config groq_config.json --mcp-config mcp_config.json'
